filebeat.inputs:
  # Backend application logs
  - type: log
    enabled: true
    paths:
      - /var/log/backend/*.log
    fields:
      service: backend
      environment: ${ENVIRONMENT:development}
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true
    multiline.pattern: '^\{'
    multiline.negate: true
    multiline.match: after

  # Celery worker logs
  - type: log
    enabled: true
    paths:
      - /var/log/celery/*.log
    fields:
      service: celery
      environment: ${ENVIRONMENT:development}
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true

  # Docker container logs
  - type: container
    enabled: true
    paths:
      - '/var/lib/docker/containers/*/*.log'
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      - decode_json_fields:
          fields: ["message"]
          target: ""
          overwrite_keys: true

# Output to Elasticsearch
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "ai-assistant-logs-%{+yyyy.MM.dd}"
  template.name: "ai-assistant"
  template.pattern: "ai-assistant-logs-*"
  template.settings:
    index.number_of_shards: 1
    index.number_of_replicas: 0
    index.refresh_interval: "5s"

# Logging configuration
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

# Processors for log enrichment
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - timestamp:
      field: timestamp
      layouts:
        - '2006-01-02T15:04:05.000Z'
        - '2006-01-02T15:04:05Z'
      test:
        - '2023-12-01T10:30:45.123Z'

# Index lifecycle management
setup.ilm.enabled: true
setup.ilm.rollover_alias: "ai-assistant-logs"
setup.ilm.pattern: "ai-assistant-logs-*"
setup.ilm.policy: "ai-assistant-policy"

# Kibana dashboard setup
setup.dashboards.enabled: true
setup.kibana:
  host: "kibana:5601"

# Template settings
setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
  _source.enabled: true