"""add_performance_indexes

Revision ID: f321e710be69
Revises: 002_add_password_hash
Create Date: 2026-04-19 13:57:17.823918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f321e710be69'
down_revision = '002_add_password_hash'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_logs_user_id_created_at', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_calendars_user_id'), 'calendars', ['user_id'], unique=False)
    op.drop_index('idx_events_user_id_start_time', table_name='events')
    op.create_index(op.f('ix_events_calendar_id'), 'events', ['calendar_id'], unique=False)
    op.create_index(op.f('ix_events_start_time'), 'events', ['start_time'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.drop_index('idx_federated_rounds_round_number', table_name='federated_rounds')
    op.drop_index('idx_tasks_user_id_status', table_name='tasks')
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.drop_index('idx_users_email', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('idx_whatsapp_messages_thread_id_sent_at', table_name='whatsapp_messages')
    op.create_index(op.f('ix_whatsapp_messages_sent_at'), 'whatsapp_messages', ['sent_at'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_thread_id'), 'whatsapp_messages', ['thread_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_threads_phone_number'), 'whatsapp_threads', ['phone_number'], unique=False)
    op.create_index(op.f('ix_whatsapp_threads_user_id'), 'whatsapp_threads', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_threads_user_id'), table_name='whatsapp_threads')
    op.drop_index(op.f('ix_whatsapp_threads_phone_number'), table_name='whatsapp_threads')
    op.drop_index(op.f('ix_whatsapp_messages_thread_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_sent_at'), table_name='whatsapp_messages')
    op.create_index('idx_whatsapp_messages_thread_id_sent_at', 'whatsapp_messages', ['thread_id', 'sent_at'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.create_index('idx_tasks_user_id_status', 'tasks', ['user_id', 'status'], unique=False)
    op.create_index('idx_federated_rounds_round_number', 'federated_rounds', ['round_number'], unique=False)
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_start_time'), table_name='events')
    op.drop_index(op.f('ix_events_calendar_id'), table_name='events')
    op.create_index('idx_events_user_id_start_time', 'events', ['user_id', 'start_time'], unique=False)
    op.drop_index(op.f('ix_calendars_user_id'), table_name='calendars')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.create_index('idx_audit_logs_user_id_created_at', 'audit_logs', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###